# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/da949990/fpga_design_5722/lab_4/vga_key.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
